name: Task 4
description: Manage a backend component for the project
title: "[feat] Create a new user"
labels: ["backend"]
assignees:
  - AdamsGeeky
body:
  - type: textarea
    attributes:
      label: Component Description
      description: Describe the purpose and functionality of the backend component.
      placeholder: Explain what this component is responsible for.
      value: |
        Add a `POST /users` endpoint to create a new user in the DB.
  - type: textarea
    attributes:
      label: API Routes
      description: Describe API routes together with purpose and functionality
      value: |
        - Return errors for missing `email` or `password`.
        - Return error if `email` already exists.
        - Hash the password using `SHA1`.
        - Save user to `users` collection.
        - Return the new user with `email` and `id`.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Data Flow
      description: Describe data flow together with purpose and functionality
      value: |
        - Data is received from clients via API requests.
        - The component processes the data and interacts with the database.
        - Processed data is returned to clients as API responses.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
